export enum listActions {
     FETCH_USER_LISTS = 'FETCH_USER_LISTS',
     CLEAR_STATE = 'CLEAR_STATE',
     ADD_NEW_LIST_NAME = 'ADD_NEW_LIST_NAME',
     ADD_NEW_ITEM_IN_LIST = 'ADD_NEW_ITEM_IN_LIST',
     SELECT_CURRENT_LIST = 'SELECT_CURRENT_LIST',
     DELETE_LIST = 'DELETE_LIST',
     DELETE_LIST_ITEM = 'DELETE_LIST_ITEM',
     SELECT_CURRENT_ITEM_FOR_EDITING ='SELECT_CURENT_ITEM_FOR_EDITING',
     EDIT_ITEM_NAME = 'EDIT_ITEM_NAME',
     TOGGLE_CHECK_STATUS = 'TOGGLE_CHECK_STATUS',
     CHANGE_ITEM_QUANTITY = 'CHANGE_ITEM_QUANTITY',
}