export enum userActions {
  SET_USER = 'SET_USER',
  SET_USER_MODAL_MESSAGE = 'SET_USER_MODAL_MESSAGE',
  SET_GOOGLE_CALENDAR_ACCESSS_TOKEN = 'SET_GOOGLE_CALENDAR_ACCESSS_TOKEN',
  CLEAR_GOOGLE_CALENDAR_ACCESSS_TOKEN = 'CLEAR_GOOGLE_CALENDAR_ACCESSS_TOKEN',
}
